---
title: "Study Area by Region"
author: "Marie Bouffard"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#---------------------------------------
# Load packages
#---------------------------------------
library(tidyverse)
library(here)
library(janitor)
library(ggsankey)
library(naniar)
library(patchwork)

#---------------------------------------
# Read in Data
#---------------------------------------

# Corcovado
raw_corcovado_87_98 <- read.csv(here("Soroush", "data_corcovado_87_98.csv")) %>% 
  clean_names()

raw_corcovado_98_19 <- read.csv(here("Soroush", "data_corcovado_98_19.csv")) %>% 
  clean_names()

# Fbs
raw_fbs_87_98 <- read.csv(here("Soroush", "data_fbs_87_98.csv")) %>% 
  clean_names()

raw_fbs_98_19 <- read.csv(here("Soroush", "data_fbs_98_19.csv")) %>% 
  clean_names()

# fonafifo
raw_fonafifo_87_98 <- read.csv(here("Soroush", "data_fonafifo_87_98.csv")) %>% 
  clean_names()

raw_fonafifo_98_19 <- read.csv(here("Soroush", "data_fonafifo_98_19.csv")) %>% 
  clean_names()

# Golfo
raw_golfo_87_98 <- read.csv(here("Soroush", "data_golfo_87_98.csv")) %>% 
  clean_names()

raw_golfo_98_19 <- read.csv(here("Soroush", "data_golfo_98_19.csv")) %>% 
  clean_names()

# Peninsula
raw_peninsula_87_98 <- read.csv(here("Soroush", "data_peninsula_87_98.csv")) %>% 
  clean_names()

raw_peninsula_98_19 <- read.csv(here("Soroush", "data_peninsula_98_19.csv")) %>% 
  clean_names()

# Piedras
raw_piedras_87_98 <- read.csv(here("Soroush", "data_piedras_87_98.csv")) %>% 
  clean_names()

raw_piedras_98_19 <- read.csv(here("Soroush", "data_piedras_98_19.csv")) %>% 
  clean_names()

# Terra
raw_terra_87_98 <- read.csv(here("Soroush", "data_terra_87_98.csv")) %>% 
  clean_names()

raw_terra_98_19 <- read.csv(here("Soroush", "data_terra_98_19.csv")) %>% 
  clean_names()

#---------------------------------------
# Pallets
#---------------------------------------
class_pallete <- c("#feebbe", # Exposed Soil
                   "#287404", # Forest
                   "#e9ffbe", # Grassland
                   "#74ffdf", # Mangrove
                   "#ffff01", # Palm
                   "#e60f03", # Teak
                   "#0d5de6", # Water
                   "#bed2ff" # Wetland
                   )

no_teak_pallete <- c("#feebbe", # Exposed Soil
                   "#287404", # Forest
                   "#e9ffbe", # Grassland
                   "#74ffdf", # Mangrove
                   "#ffff01", # Palm
                   # "#e60f03", # Teak
                   "#0d5de6", # Water
                   "#bed2ff" # Wetland
                   )
```


### Corcovado

```{r, cache=TRUE}
#---------------------------------------
# Tidy Data
#---------------------------------------
#1987 to 1998
corcovado_tidy_87_98 <- raw_corcovado_87_98 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_1998",
               values_to = "change") %>% 
  rename("lu_1987" = land_use) %>% 
  mutate(lu_1998 = case_when(
    lu_1998 == "palm" ~ "Palm",
    lu_1998 == "mangrove" ~ "Mangrove",
    lu_1998 == "water" ~ "Water",
    lu_1998 == "grassland" ~ "Grassland",
    lu_1998 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_1998 == "primary_forest" ~ "Forest",
    lu_1998 == "teak_melina" ~ "Teak / Melina",
    lu_1998 == "wetland" ~ "Wetland")) %>% 
    select(lu_1987, lu_1998, change) 

#1998 to 2019
corcovado_tidy_98_19 <- raw_corcovado_98_19 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_2019",
               values_to = "change") %>% 
  rename("lu_1998" = land_use) %>% 
  mutate(lu_2019 = case_when(
    lu_2019 == "palm" ~ "Palm",
    lu_2019 == "mangrove" ~ "Mangrove",
    lu_2019 == "water" ~ "Water",
    lu_2019 == "grassland" ~ "Grassland",
    lu_2019 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_2019 == "primary_forest" ~ "Forest",
    lu_2019 == "teak_melina" ~ "Teak / Melina",
    lu_2019 == "wetland" ~ "Wetland")) %>% 
    select(lu_1998, lu_2019, change) 

#---------------------------------------
# Uncount
#---------------------------------------
# 1987 to 1998
corcovado_uncount_87_98 <- corcovado_tidy_87_98 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# 1998 to 2019
corcovado_uncount_98_19 <- corcovado_tidy_98_19 %>% 
  mutate(change = round(change, digits = 0)) %>%
  uncount(change)

#---------------------------------------
# Make long
#---------------------------------------
# 1987 to 1998
# corcovado_long_87_98 <- corcovado_uncount_87_98 %>% 
#   make_long(lu_1987:lu_1998)

# 1998 to 2019
# corcovado_long_98_19 <- corcovado_uncount_98_19 %>% 
#   make_long(lu_1998:lu_2019)

#---------------------------------------
# Combine
#---------------------------------------
# Export to run combiner.exe
# write.csv(corcovado_uncount_87_98,"set1.csv")
# write.csv(corcovado_uncount_98_19,"set2.csv")

# Read in combined csvs
corcovado_combined <- read.csv(here("Intermediate Data", "Corcovado", "combinedSet.csv"))

# Make long
corcovado_long_combined <- corcovado_combined %>% 
  make_long(lu_1987:lu_2019)

```

### Sustainable Biodiversity Fund (FBS)

```{r, cache=TRUE}
#---------------------------------------
# Tidy Data
#---------------------------------------
#1987 to 1998
fbs_tidy_87_98 <- raw_fbs_87_98 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_1998",
               values_to = "change") %>% 
  rename("lu_1987" = land_use) %>% 
  mutate(lu_1998 = case_when(
    lu_1998 == "palm" ~ "Palm",
    lu_1998 == "mangrove" ~ "Mangrove",
    lu_1998 == "water" ~ "Water",
    lu_1998 == "grassland" ~ "Grassland",
    lu_1998 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_1998 == "primary_forest" ~ "Forest",
    lu_1998 == "teak_melina" ~ "Teak / Melina",
    lu_1998 == "wetland" ~ "Wetland")) %>% 
    select(lu_1987, lu_1998, change) 

#1998 to 2019
fbs_tidy_98_19 <- raw_fbs_98_19 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_2019",
               values_to = "change") %>% 
  rename("lu_1998" = land_use) %>% 
  mutate(lu_2019 = case_when(
    lu_2019 == "palm" ~ "Palm",
    lu_2019 == "mangrove" ~ "Mangrove",
    lu_2019 == "water" ~ "Water",
    lu_2019 == "grassland" ~ "Grassland",
    lu_2019 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_2019 == "primary_forest" ~ "Forest",
    lu_2019 == "teak_melina" ~ "Teak / Melina",
    lu_2019 == "wetland" ~ "Wetland")) %>% 
    select(lu_1998, lu_2019, change) 

#---------------------------------------
# Uncount
#---------------------------------------
# 1987 to 1998
fbs_uncount_87_98 <- fbs_tidy_87_98 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# 1998 to 2019
fbs_uncount_98_19 <- fbs_tidy_98_19 %>% 
  mutate(change = round(change, digits = 0)) %>%
  uncount(change)

#---------------------------------------
# Make long
#---------------------------------------
# 1987 to 1998
# fbs_long_87_98 <- fbs_uncount_87_98 %>% 
#   make_long(lu_1987:lu_1998)

# 1998 to 2019
# fbs_long_98_19 <- fbs_uncount_98_19 %>% 
#   make_long(lu_1998:lu_2019)

#---------------------------------------
# Combine
#---------------------------------------
# Export to run combiner.exe
# write.csv(fbs_uncount_87_98,"set1.csv")
# write.csv(fbs_uncount_98_19,"set2.csv")

# Read in combined csvs
fbs_combined <- read.csv(here("Intermediate Data", "Fbs", "combinedSet.csv")) %>% 
  replace_with_na(replace = list(lu_1987 = "n/a")) 

# Make long
fbs_long_combined <- fbs_combined %>% 
  make_long(lu_1987:lu_2019)

```

### Fonafifo

```{r, cache=TRUE}
#---------------------------------------
# Tidy Data
#---------------------------------------
#1987 to 1998
fonafifo_tidy_87_98 <- raw_fonafifo_87_98 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_1998",
               values_to = "change") %>% 
  rename("lu_1987" = land_use) %>% 
  mutate(lu_1998 = case_when(
    lu_1998 == "palm" ~ "Palm",
    lu_1998 == "mangrove" ~ "Mangrove",
    lu_1998 == "water" ~ "Water",
    lu_1998 == "grassland" ~ "Grassland",
    lu_1998 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_1998 == "primary_forest" ~ "Forest",
    lu_1998 == "teak_melina" ~ "Teak / Melina",
    lu_1998 == "wetland" ~ "Wetland")) %>% 
    select(lu_1987, lu_1998, change) 

#1998 to 2019
fonafifo_tidy_98_19 <- raw_fonafifo_98_19 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_2019",
               values_to = "change") %>% 
  rename("lu_1998" = land_use) %>% 
  mutate(lu_2019 = case_when(
    lu_2019 == "palm" ~ "Palm",
    lu_2019 == "mangrove" ~ "Mangrove",
    lu_2019 == "water" ~ "Water",
    lu_2019 == "grassland" ~ "Grassland",
    lu_2019 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_2019 == "primary_forest" ~ "Forest",
    lu_2019 == "teak_melina" ~ "Teak / Melina",
    lu_2019 == "wetland" ~ "Wetland")) %>% 
    select(lu_1998, lu_2019, change) 

#---------------------------------------
# Uncount
#---------------------------------------
# 1987 to 1998
fonafifo_uncount_87_98 <- fonafifo_tidy_87_98 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# 1998 to 2019
fonafifo_uncount_98_19 <- fonafifo_tidy_98_19 %>% 
  mutate(change = round(change, digits = 0)) %>%
  uncount(change)

#---------------------------------------
# Make long
#---------------------------------------
# 1987 to 1998
# fonafifo_long_87_98 <- fonafifo_uncount_87_98 %>% 
#   make_long(lu_1987:lu_1998)

# 1998 to 2019
# fonafifo_long_98_19 <- fonafifo_uncount_98_19 %>% 
#   make_long(lu_1998:lu_2019)

#---------------------------------------
# Combine
#---------------------------------------
# Export to run combiner.exe
# write.csv(fonafifo_uncount_87_98,"set1.csv")
# write.csv(fonafifo_uncount_98_19,"set2.csv")

# Read in combined csvs
fonafifo_combined <- read.csv(here("Intermediate Data", "Fonafifo", "combinedSet.csv")) %>% 
  replace_with_na(replace = list(lu_1987 = "n/a")) 

# Make long
fonafifo_long_combined <- fonafifo_combined %>% 
  make_long(lu_1987:lu_2019)

```

### Golfo Dulce

```{r, cache=TRUE}
#---------------------------------------
# Tidy Data
#---------------------------------------
#1987 to 1998
golfo_tidy_87_98 <- raw_golfo_87_98 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_1998",
               values_to = "change") %>% 
  rename("lu_1987" = land_use) %>% 
  mutate(lu_1998 = case_when(
    lu_1998 == "palm" ~ "Palm",
    lu_1998 == "mangrove" ~ "Mangrove",
    lu_1998 == "water" ~ "Water",
    lu_1998 == "grassland" ~ "Grassland",
    lu_1998 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_1998 == "primary_forest" ~ "Forest",
    lu_1998 == "teak_melina" ~ "Teak / Melina",
    lu_1998 == "wetland" ~ "Wetland")) %>% 
    select(lu_1987, lu_1998, change) 

#1998 to 2019
golfo_tidy_98_19 <- raw_golfo_98_19 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_2019",
               values_to = "change") %>% 
  rename("lu_1998" = land_use) %>% 
  mutate(lu_2019 = case_when(
    lu_2019 == "palm" ~ "Palm",
    lu_2019 == "mangrove" ~ "Mangrove",
    lu_2019 == "water" ~ "Water",
    lu_2019 == "grassland" ~ "Grassland",
    lu_2019 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_2019 == "primary_forest" ~ "Forest",
    lu_2019 == "teak_melina" ~ "Teak / Melina",
    lu_2019 == "wetland" ~ "Wetland")) %>% 
    select(lu_1998, lu_2019, change) 

#---------------------------------------
# Uncount
#---------------------------------------
# 1987 to 1998
golfo_uncount_87_98 <- golfo_tidy_87_98 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# 1998 to 2019
golfo_uncount_98_19 <- golfo_tidy_98_19 %>% 
  mutate(change = round(change, digits = 0)) %>%
  uncount(change)

#---------------------------------------
# Make long
#---------------------------------------
# 1987 to 1998
# golfo_long_87_98 <- golfo_uncount_87_98 %>% 
#   make_long(lu_1987:lu_1998)

# 1998 to 2019
# golfo_long_98_19 <- golfo_uncount_98_19 %>% 
#   make_long(lu_1998:lu_2019)

#---------------------------------------
# Combine
#---------------------------------------
# Export to run combiner.exe
# write.csv(golfo_uncount_87_98,"set1.csv")
# write.csv(golfo_uncount_98_19,"set2.csv")

# Read in combined csvs
golfo_combined <- read.csv(here("Intermediate Data", "Golfo", "combinedSet.csv")) %>% 
  replace_with_na(replace = list(lu_1987 = "n/a")) 

# Make long
golfo_long_combined <- golfo_combined %>% 
  make_long(lu_1987:lu_2019)

```

### Piedras Blancas

```{r, cache=TRUE}
#---------------------------------------
# Tidy Data
#---------------------------------------
#1987 to 1998
piedras_tidy_87_98 <- raw_piedras_87_98 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_1998",
               values_to = "change") %>% 
  rename("lu_1987" = land_use) %>% 
  mutate(lu_1998 = case_when(
    lu_1998 == "palm" ~ "Palm",
    lu_1998 == "mangrove" ~ "Mangrove",
    lu_1998 == "water" ~ "Water",
    lu_1998 == "grassland" ~ "Grassland",
    lu_1998 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_1998 == "primary_forest" ~ "Forest",
    lu_1998 == "teak_melina" ~ "Teak / Melina",
    lu_1998 == "wetland" ~ "Wetland")) %>% 
    select(lu_1987, lu_1998, change) 

#1998 to 2019
piedras_tidy_98_19 <- raw_piedras_98_19 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_2019",
               values_to = "change") %>% 
  rename("lu_1998" = land_use) %>% 
  mutate(lu_2019 = case_when(
    lu_2019 == "palm" ~ "Palm",
    lu_2019 == "mangrove" ~ "Mangrove",
    lu_2019 == "water" ~ "Water",
    lu_2019 == "grassland" ~ "Grassland",
    lu_2019 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_2019 == "primary_forest" ~ "Forest",
    lu_2019 == "teak_melina" ~ "Teak / Melina",
    lu_2019 == "wetland" ~ "Wetland")) %>% 
    select(lu_1998, lu_2019, change) 

#---------------------------------------
# Uncount
#---------------------------------------
# 1987 to 1998
piedras_uncount_87_98 <- piedras_tidy_87_98 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# 1998 to 2019
piedras_uncount_98_19 <- piedras_tidy_98_19 %>% 
  mutate(change = round(change, digits = 0)) %>%
  uncount(change)

#---------------------------------------
# Make long
#---------------------------------------
# 1987 to 1998
# piedras_long_87_98 <- piedras_uncount_87_98 %>% 
#   make_long(lu_1987:lu_1998)

# 1998 to 2019
# piedras_long_98_19 <- piedras_uncount_98_19 %>% 
#   make_long(lu_1998:lu_2019)

#---------------------------------------
# Combine
#---------------------------------------
# Export to run combiner.exe
write.csv(piedras_uncount_87_98,"set1.csv")
write.csv(piedras_uncount_98_19,"set2.csv")

# Read in combined csvs
piedras_combined <- read.csv(here("Intermediate Data", "Piedras", "combinedSet.csv")) %>% 
  replace_with_na(replace = list(lu_1987 = "n/a")) 

# Make long
piedras_long_combined <- piedras_combined %>% 
  make_long(lu_1987:lu_2019)

```

### Terra Sierpe

```{r, cache=TRUE}
#---------------------------------------
# Tidy Data
#---------------------------------------
#1987 to 1998
terra_tidy_87_98 <- raw_terra_87_98 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_1998",
               values_to = "change") %>% 
  rename("lu_1987" = land_use) %>% 
  mutate(lu_1998 = case_when(
    lu_1998 == "palm" ~ "Palm",
    lu_1998 == "mangrove" ~ "Mangrove",
    lu_1998 == "water" ~ "Water",
    lu_1998 == "grassland" ~ "Grassland",
    lu_1998 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_1998 == "primary_forest" ~ "Forest",
    lu_1998 == "teak_melina" ~ "Teak / Melina",
    lu_1998 == "wetland" ~ "Wetland")) %>% 
    select(lu_1987, lu_1998, change) 

#1998 to 2019
terra_tidy_98_19 <- raw_terra_98_19 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "lu_2019",
               values_to = "change") %>% 
  rename("lu_1998" = land_use) %>% 
  mutate(lu_2019 = case_when(
    lu_2019 == "palm" ~ "Palm",
    lu_2019 == "mangrove" ~ "Mangrove",
    lu_2019 == "water" ~ "Water",
    lu_2019 == "grassland" ~ "Grassland",
    lu_2019 == "exposed_soil_urban" ~ "Exposed soil / Urban",
    lu_2019 == "primary_forest" ~ "Forest",
    lu_2019 == "teak_melina" ~ "Teak / Melina",
    lu_2019 == "wetland" ~ "Wetland")) %>% 
    select(lu_1998, lu_2019, change) 

#---------------------------------------
# Uncount
#---------------------------------------
# 1987 to 1998
terra_uncount_87_98 <- terra_tidy_87_98 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# 1998 to 2019
terra_uncount_98_19 <- terra_tidy_98_19 %>% 
  mutate(change = round(change, digits = 0)) %>%
  uncount(change)

#---------------------------------------
# Make long
#---------------------------------------
# 1987 to 1998
# terra_long_87_98 <- terra_uncount_87_98 %>% 
#   make_long(lu_1987:lu_1998)

# 1998 to 2019
# terra_long_98_19 <- terra_uncount_98_19 %>% 
#   make_long(lu_1998:lu_2019)

#---------------------------------------
# Combine
#---------------------------------------
# Export to run combiner.exe
write.csv(terra_uncount_87_98,"set1.csv")
write.csv(terra_uncount_98_19,"set2.csv")

# Read in combined csvs
terra_combined <- read.csv(here("Intermediate Data", "Terra", "combinedSet.csv")) %>% 
  replace_with_na(replace = list(lu_1987 = "n/a")) 

# Make long
terra_long_combined <- terra_combined %>% 
  make_long(lu_1987:lu_2019)

```

```{r}
#---------------------------------------
# Plots
#---------------------------------------

# Corcovado
#---------------------------------------
corcovado_plot <- ggplot(data = corcovado_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

corcovado_plot

# Save
ggsave(here("Images", "corcovado_sankey.jpeg"), corcovado_plot, width = 8, height = 7)

# Fbs
#---------------------------------------
fbs_plot <- ggplot(data = fbs_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

fbs_plot

# Save
ggsave(here("Images", "fbs_sankey.jpeg"), fbs_plot, width = 8, height = 7)

# Fonafifo
#---------------------------------------
fonafifo_plot <- ggplot(data = fonafifo_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

fonafifo_plot

# Save
ggsave(here("Images", "fonafifo_sankey.jpeg"), fonafifo_plot, width = 8, height = 7)

# Golfo
#---------------------------------------
golfo_plot <- ggplot(data = golfo_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

golfo_plot

# Save
ggsave(here("Images", "golfo_sankey.jpeg"), golfo_plot, width = 8, height = 7)

# Piedras
#---------------------------------------
piedras_plot <- ggplot(data = piedras_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

piedras_plot

# Save
ggsave(here("Images", "piedras_sankey.jpeg"), piedras_plot, width = 8, height = 7)

# Terra
#---------------------------------------
terra_plot <- ggplot(data = terra_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = no_teak_pallete) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

terra_plot

# Save
ggsave(here("Images", "terra_sankey.jpeg"), terra_plot, width = 8, height = 7)

```
### Plots together

```{r}

# Corcovado
#---------------------------------------
corcovado_patch <- ggplot(data = corcovado_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  ggtitle("Corcovado") +
  theme_minimal() +
  coord_cartesian(clip = 'off') +
  theme(
    plot.title = element_text(size = 12, face = "bold", hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 12),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

# FBS
#---------------------------------------
fbs_patch <- ggplot(data = fbs_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  ggtitle("Sustainable Biodiversity Fund") +
  theme_minimal() +
  coord_cartesian(clip = 'off') +
  theme(
    plot.title = element_text(size = 12, face = "bold", hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 12),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

# Fonafifo
#---------------------------------------
fonafifo_patch <- ggplot(data = fonafifo_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  ggtitle("Fonafifo Farms") +
  theme_minimal() +
  coord_cartesian(clip = 'off') +
  theme(
    plot.title = element_text(size = 12, face = "bold", hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 12),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

# Golfo
#---------------------------------------
golfo_patch <- ggplot(data = golfo_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  ggtitle("Golfo Dulce") +
  coord_cartesian(clip = 'off') +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12, face = "bold", hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 12),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

# Piedras
#---------------------------------------
piedras_patch <- ggplot(data = piedras_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  ggtitle("Piedras Blancas") +
  theme_minimal() +
  coord_cartesian(clip = 'off') +
  theme(
    plot.title = element_text(size = 12, face = "bold", hjust = 0.5),
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 12),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

terra_patch <- ggplot(data = terra_long_combined, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  ggtitle("Terra Sierpe") +
  theme_minimal() +
  coord_cartesian(clip = 'off') +
  theme(
    plot.title = element_text(size = 12, face = "bold", hjust = 0.5),
    legend.position = "none",
    axis.text.x = element_text(size = 12),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    # panel.background = element_rect(fill = "white"),
    # plot.background = element_rect(fill = "white", color = NA),
    # rect = element_rect(fill = "white", color = NA)
  )

#---------------------------------------
# Patchwork
#---------------------------------------

acosa_patchwork <- (corcovado_patch | fbs_patch | fonafifo_patch) / (golfo_patch | piedras_patch | terra_patch)

acosa_patchwork

ggsave(here("Images", "acosa_patchwork.jpeg"), acosa_patchwork, width = 11, height = 7)

```

