---
title: "Protected vs Unprotected Areas Sankey"
author: "Marie Bouffard"
date: "2023-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#---------------------------------------
# Load packages
#---------------------------------------
library(tidyverse)
library(here)
library(janitor)
library(ggsankey)
library(ggalluvial)
library(networkD3)
library(htmlwidgets)
library(webshot)
library(naniar)
library(scales)
library(patchwork)

#---------------------------------------
# Read in Data
#---------------------------------------

# Combined Sets
#---------------------------------------
pa_transition <- read.csv(here("Protected_Unprotected", "PA_87_98_19_transition.csv")) %>% 
  clean_names()

nonpa_transition <- read.csv(here("Protected_Unprotected", "nonPA_87_98_19_transition.csv")) %>% 
  clean_names()

# Protected Areas
#---------------------------------------
# 1987 to 1998
pa_change_87_98 <- read.csv(here("Protected_Unprotected", "ProtectedAReas87-98.csv")) %>% 
  clean_names()

# 1998 to 2019
pa_change_98_19 <- read.csv(here("Protected_Unprotected", "ProtectedAReas98-19.csv")) %>% 
  clean_names()

# Non-protected Areas
#---------------------------------------
npa_change_87_98 <- read.csv(here("Protected_Unprotected", "NonPA87-98.csv")) %>% 
  clean_names()

# 1998 to 2019
npa_change_98_19 <- read.csv(here("Protected_Unprotected", "NonPA98-19.csv")) %>% 
  clean_names()

#---------------------------------------
# Color Palettes
#---------------------------------------
class_pallete <- c("Exposed Soil/Urban" = "#feebbe",
                   "a_Forest" = "#287404",
                   "Grassland/Pasture" = "#e9ffbe",
                   "Mangrove" = "#74ffdf",
                   "Palm" = "#ffff01",
                   "Teak/Gmelina" = "#e60f03",
                   "Water" = "#0d5de6",
                   "Wetland" = "#bed2ff"
                   )
```

```{r}
#---------------------------------------
# Format combined sets for ggsankey
#---------------------------------------

# Protected Areas
#---------------------------------------
tidy_pa_transition <- pa_transition %>% 
    mutate(lu_1987 = case_when(
    x87_landuse == 1 ~ "Palm",
    x87_landuse == 2 ~ "Mangrove",
    x87_landuse == 3 ~ "Water",
    x87_landuse == 4 ~ "Grassland/Pasture",
    x87_landuse == 5 ~ "Exposed Soil/Urban",
    x87_landuse == 6 ~ "a_Forest",
    x87_landuse == 7 ~ "a_Forest",
    x87_landuse == 8 ~ "Wetland",
    x87_landuse == 9 ~ "Teak/Gmelina"),
    lu_1998 = case_when(
      x98_landuse == 1 ~ "Palm",
      x98_landuse == 2 ~ "Mangrove",
      x98_landuse == 3 ~ "Water",
      x98_landuse == 4 ~ "Grassland/Pasture",
      x98_landuse == 5 ~ "Exposed Soil/Urban",
      x98_landuse == 6 ~ "a_Forest",
      x98_landuse == 7 ~ "a_Forest",
      x98_landuse == 8 ~ "Wetland",
      x98_landuse == 9 ~ "Teak/Gmelina"
    ),
    lu_2019 = case_when(
      x19_landuse == 1 ~ "Palm",
      x19_landuse == 2 ~ "Mangrove",
      x19_landuse == 3 ~ "Water",
      x19_landuse == 4 ~ "Grassland/Pasture",
      x19_landuse == 5 ~ "Exposed Soil/Urban",
      x19_landuse == 6 ~ "a_Forest",
      x19_landuse == 7 ~ "a_Forest",
      x19_landuse == 8 ~ "Wetland",
      x19_landuse == 9 ~ "Teak/Gmelina"
    )) %>% 
  rename("change" = ha) %>% 
  select(lu_1987, lu_1998, lu_2019, change) %>% 
  drop_na()

# Non Protected Areas
#---------------------------------------
tidy_nonpa_transition <- nonpa_transition %>% 
    mutate(lu_1987 = case_when(
    x87_landuse == 1 ~ "Palm",
    x87_landuse == 2 ~ "Mangrove",
    x87_landuse == 3 ~ "Water",
    x87_landuse == 4 ~ "Grassland/Pasture",
    x87_landuse == 5 ~ "Exposed Soil/Urban",
    x87_landuse == 6 ~ "a_Forest",
    x87_landuse == 7 ~ "a_Forest",
    x87_landuse == 8 ~ "Wetland",
    x87_landuse == 9 ~ "Teak/Gmelina"),
    lu_1998 = case_when(
      x98_landuse == 1 ~ "Palm",
      x98_landuse == 2 ~ "Mangrove",
      x98_landuse == 3 ~ "Water",
      x98_landuse == 4 ~ "Grassland/Pasture",
      x98_landuse == 5 ~ "Exposed Soil/Urban",
      x98_landuse == 6 ~ "a_Forest",
      x98_landuse == 7 ~ "a_Forest",
      x98_landuse == 8 ~ "Wetland",
      x98_landuse == 9 ~ "Teak/Gmelina"
    ),
    lu_2019 = case_when(
      x19_landuse == 1 ~ "Palm",
      x19_landuse == 2 ~ "Mangrove",
      x19_landuse == 3 ~ "Water",
      x19_landuse == 4 ~ "Grassland/Pasture",
      x19_landuse == 5 ~ "Exposed Soil/Urban",
      x19_landuse == 6 ~ "a_Forest",
      x19_landuse == 7 ~ "a_Forest",
      x19_landuse == 8 ~ "Wetland",
      x19_landuse == 9 ~ "Teak/Gmelina"
    )) %>% 
  rename("change" = ha) %>% 
  select(lu_1987, lu_1998, lu_2019, change) %>% 
  drop_na()

#---------------------------------------
# Calculate hectares of data (0s excluded)
#---------------------------------------
# Protected Areas
#---------------------------------------
pa_total_area <- tidy_pa_transition %>%
  summarise(total = sum(change))

# Non Protected Areas
#---------------------------------------
nonpa_total_area <- tidy_nonpa_transition %>%
  summarise(total = sum(change))
```

```{r}
#---------------------------------------
# Uncount Combined Sets
#---------------------------------------

# Protected Areas
#---------------------------------------
uncount_pa_transition <- tidy_pa_transition %>% 
  mutate(change = round((change*100), digits = 0)) %>% 
  uncount(change)

# Non Protected Areas
#---------------------------------------
uncount_nonpa_transition <- tidy_nonpa_transition %>% 
  mutate(change = round((change*100), digits = 0)) %>% 
  uncount(change)

```

```{r}
#---------------------------------------
# Make Long
#---------------------------------------

# Protected Areas
#---------------------------------------
pa_transition_long <- uncount_pa_transition %>% 
  make_long(lu_1987:lu_2019)

# Non Protected Areas
#---------------------------------------
nonpa_transition_long <- uncount_nonpa_transition %>% 
  make_long(lu_1987:lu_2019)

```

```{r}
pa_long_ordered <- pa_transition_long %>% 
  mutate(node = as.factor(node), levels = c(""))
```

```{r}
#---------------------------------------
# Plots
#---------------------------------------
pa_transition_plot <- ggplot(data = pa_transition_long, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
    labs(title = "Protected Areas",
       caption = "126,906 hectares") +
  theme(
    plot.title = element_text(hjust = 0.5),
    plot.caption = element_text(hjust = 0.5),
    legend.position = "none",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

pa_transition_plot

# Save
ggsave(here("Images", "protectedareas_transition_sankey.jpeg"), pa_transition_plot, width = 8, height = 7)

# Non Protected Areas
#---------------------------------------
nonpa_transition_plot <- ggplot(data = nonpa_transition_long, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
    labs(title = "Non Protected Areas",
       caption = "156,820 hectares") +
  theme(
    plot.title = element_text(hjust = 0.5),
    plot.caption = element_text(hjust = 0.5),
    legend.position = "none",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

nonpa_transition_plot

# Save
ggsave(here("Images", "nonprotectedareas_transition_sankey.jpeg"), nonpa_transition_plot, width = 8, height = 7)

# Combine
#---------------------------------------
transition_patchwork <- (pa_transition_plot | nonpa_transition_plot)

transition_patchwork

ggsave(here("Images", "graphicalabstract_patchwork_new.jpeg"), transition_patchwork, width = 7.5, height = 4)

```

### Only Changes

```{r}
#---------------------------------------
# Only cells that changed
#---------------------------------------
pa_transition_changeonly <- read.csv(here("Protected_Unprotected", "PA_Transition_ChangeOnly.csv")) %>% 
  clean_names()

nonpa_transition_changeonly <- read.csv(here("Protected_Unprotected", "NonPA_Transition_ChangeOnly.csv")) %>% 
  clean_names()

#---------------------------------------
# Calculate hectares of data
#---------------------------------------

# Protected Areas
#---------------------------------------
pa_changeonly_total_area <- pa_transition_changeonly %>%
  summarise(total = sum(change))

# Non Protected Areas
#---------------------------------------
nonpa_changeonly_total_area <- nonpa_transition_changeonly %>%
  summarise(total = sum(change))

#---------------------------------------
# Uncount Change Only
#---------------------------------------

# Protected Areas
#---------------------------------------
uncount_pa_changeonly <- pa_transition_changeonly %>% 
  mutate(change = round((change*100), digits = 0)) %>% 
  uncount(change)

# Non Protected Areas
#---------------------------------------
uncount_nonpa_changeonly <- nonpa_transition_changeonly %>% 
  mutate(change = round((change*100), digits = 0)) %>% 
  uncount(change)

#---------------------------------------
# Make Long
#---------------------------------------

# Protected Areas
#---------------------------------------
pa_changeonly_long <- uncount_pa_changeonly %>% 
  make_long(lu_1987:lu_2019)

# Non Protected Areas
#---------------------------------------
nonpa_changeonly_long <- uncount_nonpa_changeonly %>% 
  make_long(i_lu_1987:lu_2019)
  
```

Plot only changes

```{r}
#---------------------------------------
# Only Changes Plots
#---------------------------------------
pa_onlychanges_plot <- ggplot(data = pa_changeonly_long, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
    labs(title = "Protected Areas",
       subtitle = "17,863 hectares") +
  theme(
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

pa_onlychanges_plot

# Save
ggsave(here("Images", "protectedareas_onlychanges_sankey.jpeg"), pa_onlychanges_plot, width = 8, height = 7)

# Non Protected Areas
#---------------------------------------
nonpa_changeonly_plot <- ggplot(data = nonpa_changeonly_long, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("i_lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
    labs(title = "Non Protected Areas",
       subtitle = "71,692 hectares") +
  theme(
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

nonpa_changeonly_plot

# Save
ggsave(here("Images", "nonprotectedareas_changeonly_sankey.jpeg"), nonpa_changeonly_plot, width = 8, height = 7)

# Combine
#---------------------------------------
changeonly_patchwork <- (pa_onlychanges_plot | nonpa_changeonly_plot)

changeonly_patchwork

ggsave(here("Images", "graphicalabstract_patchwork_changeonly.jpeg"), changeonly_patchwork, width = 8, height = 5)

```


### Old Data

Format

```{r}
#---------------------------------------
# Format for ggsankey
#---------------------------------------

# Protected Areas
#---------------------------------------
# 1987 to 1998
tidy_pa_87_98 <- pa_change_87_98 %>% 
    mutate(lu_1987 = case_when(
    x87_landuse == 1 ~ "Palm",
    x87_landuse == 2 ~ "Mangrove",
    x87_landuse == 3 ~ "Water",
    x87_landuse == 4 ~ "Grassland/Pasture",
    x87_landuse == 5 ~ "Exposed Soil/Urban",
    x87_landuse == 6 ~ "Forest",
    x87_landuse == 7 ~ "Forest",
    x87_landuse == 8 ~ "Wetland",
    x87_landuse == 9 ~ "Teak/Gmelina"),
    lu_1998 = case_when(
      x98_landuse == 1 ~ "Palm",
      x98_landuse == 2 ~ "Mangrove",
      x98_landuse == 3 ~ "Water",
      x98_landuse == 4 ~ "Grassland/Pasture",
      x98_landuse == 5 ~ "Exposed Soil/Urban",
      x98_landuse == 6 ~ "Forest",
      x98_landuse == 7 ~ "Forest",
      x98_landuse == 8 ~ "Wetland",
      x98_landuse == 9 ~ "Teak/Gmelina"
    )) %>% 
  rename("change" = ha) %>% 
  select(lu_1987, lu_1998, change) %>% 
  drop_na()

# 1998 to 2019
tidy_pa_98_19 <- pa_change_98_19 %>% 
  mutate(lu_1998 = case_when(
      x98_landuse == 1 ~ "Palm",
      x98_landuse == 2 ~ "Mangrove",
      x98_landuse == 3 ~ "Water",
      x98_landuse == 4 ~ "Grassland/Pasture",
      x98_landuse == 5 ~ "Exposed Soil/Urban",
      x98_landuse == 6 ~ "Forest",
      x98_landuse == 7 ~ "Forest",
      x98_landuse == 8 ~ "Wetland",
      x98_landuse == 9 ~ "Teak/Gmelina"
    ),
    lu_2019 = case_when(
      x19_landuse == 1 ~ "Palm",
      x19_landuse == 2 ~ "Mangrove",
      x19_landuse == 3 ~ "Water",
      x19_landuse == 4 ~ "Grassland/Pasture",
      x19_landuse == 5 ~ "Exposed Soil/Urban",
      x19_landuse == 6 ~ "Forest",
      x19_landuse == 7 ~ "Forest",
      x19_landuse == 8 ~ "Wetland",
      x19_landuse == 9 ~ "Teak/Gmelina"
    )) %>% 
  rename("change" = ha) %>% 
  select(lu_1998, lu_2019, change) %>% 
  drop_na()

# Non Protected Areas
#---------------------------------------
# 1987 to 1998
tidy_npa_87_98 <- npa_change_87_98 %>% 
  mutate(lu_1987 = case_when(
    x87_landuse == 1 ~ "Palm",
    x87_landuse == 2 ~ "Mangrove",
    x87_landuse == 3 ~ "Water",
    x87_landuse == 4 ~ "Grassland/Pasture",
    x87_landuse == 5 ~ "Exposed Soil/Urban",
    x87_landuse == 6 ~ "Forest",
    x87_landuse == 7 ~ "Forest",
    x87_landuse == 8 ~ "Wetland",
    x87_landuse == 9 ~ "Teak/Gmelina"),
    lu_1998 = case_when(
      x98_landuse == 1 ~ "Palm",
      x98_landuse == 2 ~ "Mangrove",
      x98_landuse == 3 ~ "Water",
      x98_landuse == 4 ~ "Grassland/Pasture",
      x98_landuse == 5 ~ "Exposed Soil/Urban",
      x98_landuse == 6 ~ "Forest",
      x98_landuse == 7 ~ "Forest",
      x98_landuse == 8 ~ "Wetland",
      x98_landuse == 9 ~ "Teak/Gmelina"
    )) %>% 
  rename("change" = ha_non_protected) %>% 
  select(lu_1987, lu_1998, change) %>% 
  drop_na()

# 1998 to 2019
tidy_npa_98_19 <- npa_change_98_19 %>% 
  mutate(lu_1998 = case_when(
      x98_landuse == 1 ~ "Palm",
      x98_landuse == 2 ~ "Mangrove",
      x98_landuse == 3 ~ "Water",
      x98_landuse == 4 ~ "Grassland/Pasture",
      x98_landuse == 5 ~ "Exposed Soil/Urban",
      x98_landuse == 6 ~ "Forest",
      x98_landuse == 7 ~ "Forest",
      x98_landuse == 8 ~ "Wetland",
      x98_landuse == 9 ~ "Teak/Gmelina"
    ),
    lu_2019 = case_when(
      x19_landuse == 1 ~ "Palm",
      x19_landuse == 2 ~ "Mangrove",
      x19_landuse == 3 ~ "Water",
      x19_landuse == 4 ~ "Grassland/Pasture",
      x19_landuse == 5 ~ "Exposed Soil/Urban",
      x19_landuse == 6 ~ "Forest",
      x19_landuse == 7 ~ "Forest",
      x19_landuse == 8 ~ "Wetland",
      x19_landuse == 9 ~ "Teak/Gmelina"
    )) %>% 
  rename("change" = ha_non_protected) %>% 
  select(lu_1998, lu_2019, change) %>% 
  drop_na()

#---------------------------------------
# Uncount
#---------------------------------------

# Protected Areas
#---------------------------------------
# 1987 to 1998
uncount_pa_87_98 <- tidy_pa_87_98 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# 1998 to 2019
uncount_pa_98_19 <- tidy_pa_98_19 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# Non Protected Areas
#---------------------------------------
# 1987 to 1998
uncount_npa_87_98 <- tidy_npa_87_98 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# 1998 to 2019
uncount_npa_98_19 <- tidy_npa_98_19 %>% 
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

```

Combine

```{r}
#---------------------------------------
# Combine
#---------------------------------------
# Create set1 and set 2 CSVs
# Move CSVs into Intermediate Data folder > subset folder e.g. "Protected"
# Open CSVs and delete the first column
# Move Combiner.exe into subset folder and run to produc combined set csv

# Protected Areas
#---------------------------------------
# Export to run combiner.exe
# write.csv(uncount_pa_87_98,"set1.csv")
# write.csv(uncount_pa_98_19,"set2.csv")

# Read in combined csvs
pa_combined <- read.csv(here("Intermediate Data", "Protected", "combinedSet.csv"))
  # replace_with_na(replace = list(lu_1987 = "n/a"))

# Non Protected Areas
#---------------------------------------
# Export to run combiner.exe
# write.csv(uncount_npa_87_98,"set1.csv")
# write.csv(uncount_npa_98_19,"set2.csv")

# Read in combined csvs
npa_combined <- read.csv(here("Intermediate Data", "NonProtected", "combinedSet.csv"))
  # replace_with_na(replace = list(lu_1987 = "n/a"))

```

Make Long

```{r}
#---------------------------------------
# Make Long
#---------------------------------------

# Protected Areas
#---------------------------------------
pa_long <- pa_combined %>% 
  make_long(lu_1987:lu_2019)

# Non Protected Areas
#---------------------------------------
npa_long <- npa_combined %>% 
  make_long(lu_1987:lu_2019)

```

Plots

```{r}
#---------------------------------------
# Plots
#---------------------------------------

# Protected Areas
#---------------------------------------
protected_plot <- ggplot(data = pa_long, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  labs(title = "Protected Areas") +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

protected_plot

# Save
ggsave(here("Images", "protected_sankey.jpeg"), protected_plot, width = 8, height = 7)

# Non Protected Areas
#---------------------------------------
nonprotected_plot <- ggplot(data = npa_long, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  labs(title = "Non Protected Areas") +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

nonprotected_plot

# Save
ggsave(here("Images", "nonprotected_sankey.jpeg"), nonprotected_plot, width = 8, height = 7)

```

Patchwork

```{r}
#---------------------------------------
# Patchwork
#---------------------------------------

# Protected Areas
protected_patch <- ggplot(data = pa_long, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  labs(title = "Protected Areas") +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

# Non Protected Areas
nonprotected_patch <- ggplot(data = npa_long, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  labs(title = "Non Protected Areas") +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

# Combine
#---------------------------------------
protected_nonprotected_patchwork <- (protected_patch / nonprotected_patch)

protected_nonprotected_patchwork 

ggsave(here("Images", "graphicalabstract_patchwork.jpeg"), protected_nonprotected_patchwork, width = 5, height = 8)

```

