---
title: "Land Use/Land Cover Change"
author: "Marie Bouffard"
date: '2022-04-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.path = "graph/")

# Load packages
#---------------------------------------
library(tidyverse)
library(here)
library(janitor)
library(ggsankey)
library(ggalluvial)
library(networkD3)
library(htmlwidgets)
library(webshot)
library(naniar)

# Read in Data
#---------------------------------------

# 1987 to 1998
lu_change_87_98 <- read.csv(here("Soroush", "data_whole_87_98.csv")) %>% 
  clean_names()

# 1998 to 2019
lu_change_98_19 <- read.csv(here("Soroush", "data_whole_98_19.csv")) %>% 
  clean_names()

# Tidy Change Data
#---------------------------------------
# 1987 to 1998
tidy_87_98 <- lu_change_87_98 %>% 
  pivot_longer(!land_use:area_starting_year, names_to = "target",
               values_to = "change") %>% 
  rename("source" = land_use) %>% 
  mutate(target = case_when(
    target == "palm" ~ "Palm",
    target == "mangrove" ~ "Mangrove",
    target == "water" ~ "Water",
    target == "grassland" ~ "Grassland",
    target == "exposed_soil_urban" ~ "Exposed soil / Urban",
    target == "primary_forest" ~ "Forest",
    target == "teak_melina" ~ "Teak / Melina",
    target == "wetland" ~ "Wetland")) %>% 
  select(source, target, change)

# write.csv(change_87_98_tidy,"change_87_98.csv")

#1998 to 2019
tidy_98_19 <- lu_change_98_19 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "target",
               values_to = "change") %>% 
  rename("source" = land_use) %>% 
  mutate(target = case_when(
    target == "palm" ~ "Palm",
    target == "mangrove" ~ "Mangrove",
    target == "water" ~ "Water",
    target == "grassland" ~ "Grassland",
    target == "exposed_soil_urban" ~ "Exposed soil / Urban",
    target == "primary_forest" ~ "Forest",
    target == "teak_melina" ~ "Teak / Melina",
    target == "wetland" ~ "Wetland")) %>% 
    select(source, target, change) 

# write.csv(change_98_19_tidy,"change_98_19.csv")

```

ggsankey

```{r, cache = TRUE}

#---------------------------------------
# Format for ggsankey
#---------------------------------------

# 1987 to 1998
sankey_87_98 <- tidy_87_98 %>% 
  rename("lu_1987" = source) %>% 
  rename("lu_1998" = target)

# 1998 to 2019
sankey_98_19 <- tidy_98_19 %>% 
  rename("lu_1998" = source) %>% 
  rename("lu_2019" = target)

# Uncount
#---------------------------------------

# 1987 to 1998
uncount_87_98 <- sankey_87_98 %>%
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# 1998 to 1998
uncount_98_19 <- sankey_98_19 %>%
  mutate(change = round(change, digits = 0)) %>% 
  uncount(change)

# Make long
#---------------------------------------

# 1987 to 1998
long_87_98 <- uncount_87_98 %>% 
  make_long(lu_1987:lu_1998)

# 1998 to 2019
long_98_19 <- uncount_98_19 %>% 
  make_long(lu_1998:lu_2019)

# Combine
#---------------------------------------

# Combine uncounted datasets

# File too big
# uncount_combine <- full_join(uncount_87_98, uncount_98_19, by = "lu_1998")

# Export to run combiner.exe since its too big for full_join
# write.csv(uncount_87_98,"set1.csv")
# write.csv(uncount_98_19,"set2.csv")

sankey_combined <- read.csv(here("Intermediate Data", "combinedSet.csv")) %>% 
  replace_with_na(replace = list(lu_1987 = "n/a"))  

# Make Long
long_combine <- sankey_combined %>% 
  make_long(lu_1987:lu_2019)

```


```{r}

# Pallets
#---------------------------------------
class_pallete <- c("#feebbe", # Exposed Soil
                   "#287404", # Forest
                   "#e9ffbe", # Grassland
                   "#74ffdf", # Mangrove
                   "#ffff01", # Palm
                   "#e60f03", # Teak
                   "#0d5de6", # Water
                   "#bed2ff" # Wetland
                   )

#---------------------------------------
# ggsankey plots
#---------------------------------------

# 1987 to 1998
ggplot(long_87_98, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey() +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank()
  )

# 1998 to 2019
ggplot(long_98_19, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey() +
  scale_x_discrete(labels = c("lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank()
  )

# Combined
sankey_combine_plot <- ggplot(data = long_combine, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "gray30") +
  scale_x_discrete(labels = c("lu_1987" = "1987", "lu_1998" = "1998", "lu_2019" = "2019")) +
  scale_fill_manual(values = class_pallete) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.text.x = element_text(size = 14, face = "bold"),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white", color = NA),
    rect = element_rect(fill = "white", color = NA)
  )

sankey_combine_plot

# Save
ggsave(here("Images", "combined_sankey.jpeg"), sankey_combine_plot, width = 8, height = 7)

```


### networkD3

```{r}
#---------------------------------------
# Format data for networkD3
#---------------------------------------

# 1987 to 1998
change_87_98_d3 <- lu_change_87_98 %>% 
  pivot_longer(!land_use:area_starting_year, names_to = "target",
               values_to = "change") %>% 
  rename("source" = land_use) %>% 
  # select(source, target, change) %>% 
    mutate(source = case_when(
    source == "Palm" ~ "Palm 1987",
    source == "Mangrove" ~ "Mangrove 1987",
    source == "Water" ~ "Water 1987",
    source == "Grassland" ~ "Grassland 1987",
    source == "Exposed soil / Urban" ~ "Exposed soil / Urban 1987",
    source == "Forest" ~ "Forest 1987",
    source == "Teak / Melina" ~ "Teak / Melina 1987",
    source == "Wetland" ~ "Wetland 1987")) %>% 
  mutate(target = case_when(
    target == "palm" ~ "Palm 1998",
    target == "mangrove" ~ "Mangrove 1998",
    target == "water" ~ "Water 1998",
    target == "grassland" ~ "Grassland 1998",
    target == "exposed_soil_urban" ~ "Exposed soil / Urban 1998",
    target == "primary_forest" ~ "Forest 1998",
    target == "teak_melina" ~ "Teak / Melina 1998",
    target == "wetland" ~ "Wetland 1998")) %>% 
  select(source, target, change)

# write.csv(change_87_98_tidy,"change_87_98.csv")

#1998 to 2019
change_98_19_d3 <- lu_change_98_19 %>% 
    pivot_longer(!land_use:area_starting_year, names_to = "target",
               values_to = "change") %>% 
  rename("source" = land_use) %>% 
    mutate(source = case_when(
    source == "Palm" ~ "Palm 1998",
    source == "Mangrove" ~ "Mangrove 1998",
    source == "Water" ~ "Water 1998",
    source == "Grassland" ~ "Grassland 1998",
    source == "Exposed soil / Urban" ~ "Exposed soil / Urban 1998",
    source == "Forest" ~ "Forest 1998",
    source == "Teak / Melina" ~ "Teak / Melina 1998",
    source == "Wetland" ~ "Wetland 1998")) %>% 
  mutate(target = case_when(
    target == "palm" ~ "Palm 2019",
    target == "mangrove" ~ "Mangrove 2019",
    target == "water" ~ "Water 2019",
    target == "grassland" ~ "Grassland 2019",
    target == "exposed_soil_urban" ~ "Exposed soil / Urban 2019",
    target == "primary_forest" ~ "Forest 2019",
    target == "teak_melina" ~ "Teak / Melina 2019",
    target == "wetland" ~ "Wetland 2019")) %>% 
    select(source, target, change) 

# Combined
combined_d3 <- bind_rows(change_87_98_d3, change_98_19_d3) %>% 
  select(source, target, change)

```


1987 to 1998

```{r}

# A connection data frame is a list of flows with intensity for each flow
links_87_98 <- data.frame(
  source= change_87_98_d3$source,
  target= change_87_98_d3$target,
  value= change_87_98_d3$change
  ) %>% 
  mutate(group = case_when(
    source == "Palm 1987" ~ "Palm",
    source == "Mangrove 1987" ~ "Mangrove",
    source == "Water 1987" ~ "Water",
    source == "Grassland 1987" ~ "Grassland",
    source == "Exposed soil / Urban 1987" ~ "Soil",
    source == "Forest 1987" ~ "Forest",
    source == "Wetland 1987" ~ "Wetland",
    source == "Teak / Melina 1987" ~ "Teak"
  ))

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes_87_98 <- data.frame(
  name=c(as.character(links_87_98$source),
  as.character(links_87_98$target)) %>% unique()
) %>% 
  mutate(group = as.factor(c("Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak", "Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak")))

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links_87_98$IDsource <- match(links_87_98$source, nodes_87_98$name)-1
links_87_98$IDtarget <- match(links_87_98$target, nodes_87_98$name)-1

class_color <- 'd3.scaleOrdinal() .domain(["Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak"]) .range(["#ffff01", "#74ffdf" , "#0d5de6", "#e9ffbe", "#feebbe", "#287404", "#bed2ff", "#e60f03"])'

# Make the Network
plot_87_98 <- sankeyNetwork(Links = links_87_98, Nodes = nodes_87_98,
              Source = "IDsource", 
              Target = "IDtarget",
              Value = "value", 
              NodeID = "name", 
              colourScale = class_color, 
              LinkGroup = "group",  
              NodeGroup = "group",
              fontSize = 12,
              sinksRight = FALSE)

plot_87_98

htmlwidgets::onRender(plot_87_98, '
  function(el) { 
    var cols_x = this.sankey.nodes().map(d => d.x).filter((v, i, a) => a.indexOf(v) === i).sort(function(a, b){return a - b});
    var labels = ["1987", "1998"];
    cols_x.forEach((d, i) => {
      d3.select(el).select("svg")
        .append("text")
        .attr("x", d)
        .attr("y", 12)
        .text(labels[i]);
    })
  }
')

```

1998 to 2019

```{r}

# A connection data frame is a list of flows with intensity for each flow
links_98_19 <- data.frame(
  source= change_98_19_d3$source,
  target= change_98_19_d3$target,
  value= change_98_19_d3$change
  ) %>% 
  mutate(group = case_when(
    source == "Palm 1998" ~ "Palm",
    source == "Mangrove 1998" ~ "Mangrove",
    source == "Water 1998" ~ "Water",
    source == "Grassland 1998" ~ "Grassland",
    source == "Exposed soil / Urban 1998" ~ "Soil",
    source == "Forest 1998" ~ "Forest",
    source == "Wetland 1998" ~ "Wetland",
    source == "Teak / Melina 1998" ~ "Teak"
  ))

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes_98_19 <- data.frame(
  name=c(as.character(links_98_19$source),
  as.character(links_98_19$target)) %>% unique()
) %>% 
  mutate(group = as.factor(c("Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak", "Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak")))

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links_98_19$IDsource <- match(links_98_19$source, nodes_98_19$name)-1
links_98_19$IDtarget <- match(links_98_19$target, nodes_98_19$name)-1

class_color <- 'd3.scaleOrdinal() .domain(["Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak"]) .range(["#ffff01", "#74ffdf" , "#0d5de6", "#e9ffbe", "#feebbe", "#287404", "#bed2ff", "#e60f03"])'

# Make the Network
plot_98_19 <- sankeyNetwork(Links = links_98_19, Nodes = nodes_98_19,
              Source = "IDsource", 
              Target = "IDtarget",
              Value = "value", 
              NodeID = "name", 
              colourScale = class_color, 
              LinkGroup = "group",  
              NodeGroup = "group",
              fontSize = 12,
              sinksRight = FALSE)

plot_98_19

htmlwidgets::onRender(plot_98_19, '
  function(el) { 
    var cols_x = this.sankey.nodes().map(d => d.x).filter((v, i, a) => a.indexOf(v) === i).sort(function(a, b){return a - b});
    var labels = ["1998", "2019"];
    cols_x.forEach((d, i) => {
      d3.select(el).select("svg")
        .append("text")
        .attr("x", d)
        .attr("y", 12)
        .text(labels[i]);
    })
  }
')

```

Combined

```{r, fig.align='center'}

# Links
links_combined <- data.frame(
  source= combined_d3$source,
  target= combined_d3$target,
  value= combined_d3$change
  ) %>% 
  mutate(group = case_when(
    source == "Palm 1987" ~ "Palm",
    source == "Mangrove 1987" ~ "Mangrove",
    source == "Water 1987" ~ "Water",
    source == "Grassland 1987" ~ "Grassland",
    source == "Exposed soil / Urban 1987" ~ "Soil",
    source == "Forest 1987" ~ "Forest",
    source == "Wetland 1987" ~ "Wetland",
    source == "Teak / Melina 1987" ~ "Teak",
    source == "Palm 1998" ~ "Palm",
    source == "Mangrove 1998" ~ "Mangrove",
    source == "Water 1998" ~ "Water",
    source == "Grassland 1998" ~ "Grassland",
    source == "Exposed soil / Urban 1998" ~ "Soil",
    source == "Forest 1998" ~ "Forest",
    source == "Wetland 1998" ~ "Wetland",
    source == "Teak / Melina 1998" ~ "Teak"
  ))

# Nodes
nodes_combined <- data.frame(
  name=c(as.character(links_combined$source),
  as.character(links_combined$target)) %>% unique()) %>% 
  mutate(group = as.factor(c("Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak", "Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak", "Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak")))

# Color scale
class_color <- 'd3.scaleOrdinal() .domain(["Palm", "Mangrove", "Water", "Grassland", "Soil", "Forest", "Wetland", "Teak"]) .range(["#ffff01", "#74ffdf" , "#0d5de6", "#e9ffbe", "#feebbe", "#287404", "#bed2ff", "#e60f03"])'

# Format Link IDS
links_combined$IDsource <- match(links_combined$source, nodes_combined$name)-1
links_combined$IDtarget <- match(links_combined$target, nodes_combined$name)-1

# Make the Network
d3_combined_plot <- sankeyNetwork(Links = links_combined, Nodes = nodes_combined,
              Source = "IDsource", 
              Target = "IDtarget",
              Value = "value", 
              NodeID = "name", 
             colourScale = class_color,
             LinkGroup = "group",
             NodeGroup = "group",
             fontSize = 12,
             sinksRight = FALSE)

d3_combined_plot

htmlwidgets::onRender(d3_combined_plot, '
  function(el) { 
    var cols_x = this.sankey.nodes().map(d => d.x).filter((v, i, a) => a.indexOf(v) === i).sort(function(a, b){return a - b});
    var labels = ["1987", "1998", "2019"];
    cols_x.forEach((d, i) => {
      d3.select(el).select("svg")
        .append("text")
        .attr("x", d)
        .attr("y", 12)
        .text(labels[i]);
    })
  }
')

# Save image
URL <- paste0('https://cdn.rawgit.com/christophergandrud/networkD3/',
              'master/JSONdata/energy.json')
energy <- jsonlite::fromJSON(URL)

# Save as an html
saveNetwork(d3_combined_plot, "d3_combined_plot.html")

# Convert to png
webshot("d3_combined_plot.html","sankey_d3.png", vwidth = 1000, vheight = 900)

```

